from typing import Protocol

from tdp.modules.projects.domain.model import Project, ProjectId, ProjectKey


class ProjectRepository(Protocol):
    async def add(self, project: Project) -> None: ...

    async def update(self, project: Project) -> None: ...

    async def get(self, project_id: ProjectId) -> Project | None: ...

    async def get_by_key(self, key: ProjectKey) -> Project | None: ...

    async def list_all(self) -> list[Project]: ...

    async def list_by_workspace(self, workspace_id: str) -> list[Project]: ...
