from typing import Protocol

from tdp.modules.workflow.domain.model import WorkflowEvent, WorkflowItem, WorkflowItemId


class WorkflowRepository(Protocol):
    async def add(self, item: WorkflowItem) -> None: ...

    async def update(self, item: WorkflowItem, event: WorkflowEvent) -> None: ...

    async def get(self, item_id: WorkflowItemId) -> WorkflowItem | None: ...

    async def list_by_project(self, project_id: str) -> list[WorkflowItem]: ...

    async def list_events(self, item_id: WorkflowItemId) -> list[WorkflowEvent]: ...
