from typing import Protocol

from tdp.modules.workspaces.domain.model import Workspace, WorkspaceId, WorkspaceKey


class WorkspaceRepository(Protocol):
    async def add(self, workspace: Workspace) -> None: ...

    async def update(self, workspace: Workspace) -> None: ...

    async def get(self, workspace_id: WorkspaceId) -> Workspace | None: ...

    async def get_by_key(self, key: WorkspaceKey) -> Workspace | None: ...

    async def list_all(self) -> list[Workspace]: ...
