#!/usr/bin/env bash
set -euo pipefail

ROOT="$(git rev-parse --show-toplevel 2>/dev/null || true)"
if [[ -z "${ROOT}" ]]; then
  echo "ERROR: Run from inside the repository." >&2
  exit 1
fi
cd "${ROOT}"

DOWNLOADS_DIR="${HOME}/Downloads"
mkdir -p "${DOWNLOADS_DIR}"
TIMESTAMP="$(date '+%Y%m%d_%H%M%S')"
REPORT_PATH="${DOWNLOADS_DIR}/technical-documentation-platform_documentation_governance_${TIMESTAMP}.txt"
TMP_PATH="$(mktemp "${TMPDIR:-/tmp}/tdp-doc-governance.XXXXXX")"
trap 'rm -f "${TMP_PATH}"' EXIT

run_check() {
  local title="$1"
  shift
  printf '\n--- %s ---\n' "${title}" >> "${TMP_PATH}"

  set +e
  "$@" >> "${TMP_PATH}" 2>&1
  local exit_code=$?
  set -e

  printf '[exit_code=%s]\n' "${exit_code}" >> "${TMP_PATH}"
}

{
  printf '============================================================\n'
  printf 'DOCUMENTATION GOVERNANCE AND LIVING REPOSITORY DOCS AUDIT\n'
  printf '============================================================\n'
  printf 'Generated at : %s\n' "$(date '+%Y-%m-%d %H:%M:%S %Z')"
  printf 'Project root : %s\n' "${ROOT}"
  printf 'Branch       : %s\n' "$(git branch --show-current)"
  printf 'Commit       : %s\n' "$(git rev-parse HEAD)"
} > "${TMP_PATH}"

run_check "Git status" git status --short --branch
run_check "Whitespace" git diff --check
run_check "Documentation freshness" python3 scripts/generate_repository_docs.py --check
run_check "Controlled document IDs" bash -lc \
  'grep -RhoE "^\| Document ID \| [^|]+ \|$" docs/product docs/governance docs/quality docs/compliance docs/operations docs/releases docs/security docs/user-guide | sort'
run_check "Documentation portal" sed -n '1,260p' docs/README.md
run_check "Generated documentation inventory" find docs/_generated -maxdepth 1 -type f -name '*.md' -print
run_check "Generated notices" bash -lc '
  status=0
  for path in docs/_generated/*.md; do
    if ! grep -qF "Generated by scripts/generate_repository_docs.py" "$path"; then
      printf "%s\n" "$path"
      status=1
    fi
  done
  if [[ "$status" -eq 0 ]]; then
    printf "All generated documents include the generator notice.\n"
  fi
  exit "$status"
'
run_check "Architecture decision sequence" bash -lc \
  'find docs/decisions -maxdepth 1 -type f -name "ADR-*.md" -print | sort'
run_check "Requirements inventory" bash -lc \
  'find docs/requirements -maxdepth 1 -type f -name "*.md" -print | sort'
run_check "GitHub governance" bash -lc \
  'for path in .github/CODEOWNERS .github/pull_request_template.md .github/ISSUE_TEMPLATE/bug_report.yml .github/ISSUE_TEMPLATE/feature_request.yml; do test -f "$path" && echo "$path"; done'
run_check "Make documentation targets" bash -lc \
  'grep -nE "^docs:|^docs-check:|^verify:|^audit-docs:" Makefile'
run_check "Repository documentation test" \
  uv run --project backend pytest backend/tests/test_repository_documentation.py
run_check "Full repository quality gate" make verify

printf '\nSafety: .env values, SQLite data, runtime artifacts, imported sources, generated customer documents, credentials, and secrets are excluded.\n' >> "${TMP_PATH}"
printf 'Report path: %s\n' "${REPORT_PATH}" >> "${TMP_PATH}"

mv "${TMP_PATH}" "${REPORT_PATH}"
trap - EXIT

printf 'Documentation Governance audit completed.\n'
printf 'Report: %s\n' "${REPORT_PATH}"
