#!/usr/bin/env python3
"""Generate and validate repository documentation indexes deterministically."""

from __future__ import annotations

import argparse
import ast
import re
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

GENERATED_NOTICE = (
    "<!-- Generated by scripts/generate_repository_docs.py. "
    "Do not edit this file manually. -->"
)
API_PREFIX = "/api"
HTTP_METHODS = {"get", "post", "put", "patch", "delete", "options", "head"}
REQUIRED_CONTROL_FIELDS = {
    "Document ID",
    "Status",
    "Owner",
    "Classification",
    "Review cadence",
    "Source of truth",
}
CONTROLLED_DIRECTORIES = {
    "product",
    "governance",
    "quality",
    "compliance",
    "operations",
    "releases",
    "security",
    "user-guide",
}
REQUIRED_DOCUMENTS = {
    "README.md",
    "CONTRIBUTING.md",
    "SECURITY.md",
    "CHANGELOG.md",
    "docs/README.md",
    "docs/product/product-vision.md",
    "docs/product/prd.md",
    "docs/product/stakeholders-and-personas.md",
    "docs/product/user-journeys.md",
    "docs/product/user-flows.md",
    "docs/product/roadmap.md",
    "docs/architecture/README.md",
    "docs/architecture/system-context.md",
    "docs/architecture/container-view.md",
    "docs/architecture/component-view.md",
    "docs/architecture/domain-model.md",
    "docs/architecture/data-and-information-model.md",
    "docs/architecture/security-architecture.md",
    "docs/architecture/deployment-view.md",
    "docs/governance/documentation-policy.md",
    "docs/governance/document-control.md",
    "docs/governance/ownership-and-approval.md",
    "docs/governance/external-audit-response-2026-08.md",
    "docs/governance/intellectual-property-and-licensing.md",
    "docs/quality/test-strategy.md",
    "docs/quality/quality-gates.md",
    "docs/quality/traceability-model.md",
    "docs/compliance/standards-applicability.md",
    "docs/compliance/control-evidence-matrix.md",
    "docs/security/data-classification-and-retention.md",
    "docs/operations/local-development-runbook.md",
    "docs/operations/backup-and-restore.md",
    "docs/operations/incident-response.md",
    "docs/releases/release-policy.md",
    "docs/releases/release-readiness.md",
    "docs/user-guide/getting-started.md",
}
GENERATED_PATHS = {
    "docs/_generated/repository-inventory.md",
    "docs/_generated/architecture-decision-index.md",
    "docs/_generated/requirements-index.md",
    "docs/_generated/api-surface.md",
    "docs/_generated/frontend-route-index.md",
    "docs/_generated/test-inventory.md",
    "docs/_generated/document-register.md",
}


@dataclass(frozen=True)
class ApiRoute:
    method: str
    path: str
    source: str
    line: int


def repository_root() -> Path:
    return Path(__file__).resolve().parents[1]


def markdown_table(headers: list[str], rows: Iterable[Iterable[str]]) -> str:
    lines = [
        "| " + " | ".join(headers) + " |",
        "|" + "|".join("---" for _ in headers) + "|",
    ]
    for row in rows:
        lines.append("| " + " | ".join(str(value).replace("|", r"\|") for value in row) + " |")
    return "\n".join(lines)


def title_of(path: Path) -> str:
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return path.stem.replace("-", " ").replace("_", " ").title()


def control_fields(path: Path) -> dict[str, str]:
    fields: dict[str, str] = {}
    pattern = re.compile(r"^\|\s*([^|]+?)\s*\|\s*([^|]+?)\s*\|$")
    for line in path.read_text(encoding="utf-8").splitlines():
        match = pattern.match(line)
        if not match:
            continue
        key = match.group(1).strip()
        value = match.group(2).strip()
        if key not in {"Field", "---"}:
            fields[key] = value
    return fields


def adr_status(text: str) -> str:
    inline = re.search(r"(?mi)^-\s*Status:\s*(.+?)\s*$", text)
    if inline:
        return inline.group(1).strip()
    section = re.search(r"(?ms)^## Status\s*\n+(.+?)(?:\n## |\Z)", text)
    if section:
        return section.group(1).strip().splitlines()[0]
    return "Not specified"


def adr_date(text: str) -> str:
    match = re.search(r"(?mi)^-\s*Date:\s*(.+?)\s*$", text)
    return match.group(1).strip() if match else "Not specified"



def documentation_markdown_paths(
    root: Path,
    *,
    include_generated: bool,
) -> list[Path]:
    paths = [
        root / name
        for name in ("README.md", "CONTRIBUTING.md", "SECURITY.md", "CHANGELOG.md")
        if (root / name).is_file()
    ]
    docs_root = root / "docs"
    if docs_root.is_dir():
        paths.extend(
            path
            for path in docs_root.rglob("*.md")
            if include_generated or "_generated" not in path.parts
        )
    return sorted(set(paths))


def render_repository_inventory(root: Path) -> str:
    backend_modules = sorted(
        path.name
        for path in (root / "backend/src/tdp/modules").iterdir()
        if path.is_dir() and not path.name.startswith("__")
    )
    frontend_modules = sorted(
        path.name
        for path in (root / "frontend/src/modules").iterdir()
        if path.is_dir() and not path.name.startswith("__")
    )
    counts = {
        "Backend Python files": len(list((root / "backend/src").rglob("*.py"))),
        "Backend test files": len(list((root / "backend/tests").rglob("test_*.py"))),
        "Frontend TypeScript files": len(list((root / "frontend/src").rglob("*.ts"))),
        "Frontend TSX files": len(list((root / "frontend/src").rglob("*.tsx"))),
        "Frontend test files": len(
            list((root / "frontend/src").rglob("*.test.ts"))
            + list((root / "frontend/src").rglob("*.test.tsx"))
        ),
        "Controlled Markdown files": len(
            documentation_markdown_paths(root, include_generated=False)
        ),
    }
    return "\n".join(
        [
            GENERATED_NOTICE,
            "# Repository Inventory",
            "",
            "This inventory is derived from the repository tree and is checked by `make docs-check`.",
            "",
            "## Backend modules",
            "",
            *[f"- `{name}`" for name in backend_modules],
            "",
            "## Frontend modules",
            "",
            *[f"- `{name}`" for name in frontend_modules],
            "",
            "## Repository counts",
            "",
            markdown_table(["Item", "Count"], ((key, str(value)) for key, value in counts.items())),
            "",
        ]
    )


def render_adr_index(root: Path) -> str:
    rows: list[tuple[str, str, str, str]] = []
    for path in sorted((root / "docs/decisions").glob("ADR-*.md")):
        text = path.read_text(encoding="utf-8")
        identifier = path.stem.split("-", 2)[:2]
        adr_id = "-".join(identifier)
        rows.append((adr_id, title_of(path), adr_status(text), adr_date(text)))
    return "\n".join(
        [
            GENERATED_NOTICE,
            "# Architecture Decision Index",
            "",
            "Architecture decisions are human-governed. This index is generated from `docs/decisions/`.",
            "",
            markdown_table(["ADR", "Decision", "Status", "Date"], rows),
            "",
        ]
    )


def render_requirements_index(root: Path) -> str:
    rows: list[tuple[str, str, str, str, str]] = []
    for path in sorted((root / "docs/requirements").glob("*.md")):
        text = path.read_text(encoding="utf-8")
        explicit_ids = sorted(
            set(re.findall(r"\b(?:FR|NFR|REQ)-[A-Z0-9-]+\b", text))
        )
        numbered = len(re.findall(r"(?m)^\d+\.\s+", text))
        acceptance = "Yes" if re.search(r"(?mi)^## Acceptance criteria", text) else "No"
        rows.append(
            (
                path.name,
                title_of(path),
                str(len(explicit_ids)),
                str(numbered),
                acceptance,
            )
        )
    return "\n".join(
        [
            GENERATED_NOTICE,
            "# Requirements Index",
            "",
            "This index reports the requirement documents currently stored in the repository.",
            "",
            markdown_table(
                ["File", "Title", "Explicit IDs", "Numbered statements", "Acceptance criteria"],
                rows,
            ),
            "",
            "The future Requirement Registry will replace file-level counting with immutable requirement identities and revisions.",
            "",
        ]
    )


def literal_string(node: ast.AST | None) -> str | None:
    if isinstance(node, ast.Constant) and isinstance(node.value, str):
        return node.value
    return None


def discover_api_routes(root: Path) -> list[ApiRoute]:
    routes: list[ApiRoute] = []
    source_root = root / "backend/src"
    for path in sorted(source_root.rglob("*.py")):
        try:
            tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        except SyntaxError:
            continue
        prefixes: dict[str, str] = {}
        for node in ast.walk(tree):
            if not isinstance(node, (ast.Assign, ast.AnnAssign)):
                continue
            value = node.value
            if not isinstance(value, ast.Call):
                continue
            function_name = (
                value.func.id
                if isinstance(value.func, ast.Name)
                else value.func.attr
                if isinstance(value.func, ast.Attribute)
                else ""
            )
            if function_name != "APIRouter":
                continue
            prefix = ""
            for keyword in value.keywords:
                if keyword.arg == "prefix":
                    prefix = literal_string(keyword.value) or ""
            targets: list[ast.expr] = []
            if isinstance(node, ast.Assign):
                targets = node.targets
            elif node.target is not None:
                targets = [node.target]
            for target in targets:
                if isinstance(target, ast.Name):
                    prefixes[target.id] = prefix

        for node in ast.walk(tree):
            if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                continue
            for decorator in node.decorator_list:
                if not isinstance(decorator, ast.Call) or not isinstance(
                    decorator.func, ast.Attribute
                ):
                    continue
                method = decorator.func.attr.lower()
                if method not in HTTP_METHODS or not isinstance(
                    decorator.func.value, ast.Name
                ):
                    continue
                path_value = literal_string(decorator.args[0]) if decorator.args else ""
                if path_value is None:
                    continue
                router_name = decorator.func.value.id
                declared = f"{prefixes.get(router_name, '')}{path_value}"
                normalized = "/" + declared.lstrip("/")
                routes.append(
                    ApiRoute(
                        method=method.upper(),
                        path=f"{API_PREFIX}{normalized}" if normalized != "/" else API_PREFIX,
                        source=str(path.relative_to(root)),
                        line=node.lineno,
                    )
                )
    return sorted(routes, key=lambda item: (item.path, item.method, item.source, item.line))


def render_api_surface(root: Path) -> str:
    routes = discover_api_routes(root)
    rows = [
        (route.method, f"`{route.path}`", f"`{route.source}:{route.line}`")
        for route in routes
    ]
    return "\n".join(
        [
            GENERATED_NOTICE,
            "# API Surface",
            "",
            "The table is derived from FastAPI route decorators. It records declared routes, not deployment exposure or authorization.",
            "",
            markdown_table(["Method", "Path", "Source"], rows),
            "",
        ]
    )


def render_frontend_routes(root: Path) -> str:
    router_path = root / "frontend/src/app/router.ts"
    text = router_path.read_text(encoding="utf-8")
    stages_match = re.search(
        r"export const projectStages\s*=\s*\[(.*?)\]\s*as const",
        text,
        flags=re.S,
    )
    stages = (
        re.findall(r'["\']([^"\']+)["\']', stages_match.group(1))
        if stages_match
        else []
    )
    matcher_rows: list[tuple[str, str]] = []
    for match in re.finditer(
        r"const\s+([A-Za-z0-9_]+)\s*=\s*(/.*?/);",
        text,
        flags=re.S,
    ):
        pattern = " ".join(match.group(2).split())
        matcher_rows.append((match.group(1), f"`{pattern}`"))
    literal_routes = sorted(
        {
            value
            for value in re.findall(r'["\'](/[^"\']*)["\']', text)
            if not value.startswith("//")
        }
    )
    return "\n".join(
        [
            GENERATED_NOTICE,
            "# Frontend Route Index",
            "",
            "## Project workbench stages",
            "",
            *[f"- `{stage}`" for stage in stages],
            "",
            "## Router matchers",
            "",
            markdown_table(["Matcher", "Pattern"], matcher_rows),
            "",
            "## Static path literals",
            "",
            *[f"- `{route}`" for route in literal_routes],
            "",
        ]
    )


def count_python_tests(path: Path) -> int:
    text = path.read_text(encoding="utf-8")
    return len(re.findall(r"(?m)^\s*(?:async\s+)?def\s+test_[A-Za-z0-9_]+\s*\(", text))


def count_frontend_tests(path: Path) -> int:
    text = path.read_text(encoding="utf-8")
    return len(re.findall(r"(?m)\b(?:it|test)\s*\(", text))


def render_test_inventory(root: Path) -> str:
    backend_rows = [
        (str(path.relative_to(root)), str(count_python_tests(path)))
        for path in sorted((root / "backend/tests").rglob("test_*.py"))
    ]
    frontend_paths = sorted(
        set((root / "frontend/src").rglob("*.test.ts"))
        | set((root / "frontend/src").rglob("*.test.tsx"))
    )
    frontend_rows = [
        (str(path.relative_to(root)), str(count_frontend_tests(path)))
        for path in frontend_paths
    ]
    return "\n".join(
        [
            GENERATED_NOTICE,
            "# Test Inventory",
            "",
            "## Backend",
            "",
            markdown_table(["File", "Test functions"], backend_rows),
            "",
            f"Backend total: **{sum(int(row[1]) for row in backend_rows)}** tests.",
            "",
            "## Frontend",
            "",
            markdown_table(["File", "Test cases"], frontend_rows),
            "",
            f"Frontend total: **{sum(int(row[1]) for row in frontend_rows)}** tests.",
            "",
            "Counts are structural and do not replace execution evidence from `make verify`.",
            "",
        ]
    )


def document_category(path: Path, root: Path) -> str:
    relative = path.relative_to(root)
    if relative.parts[0] != "docs":
        return "Repository root"
    if len(relative.parts) < 2 or relative.name == "README.md" and len(relative.parts) == 2:
        return "Documentation"
    return relative.parts[1].replace("-", " ").title()


def render_document_register(root: Path) -> str:
    rows: list[tuple[str, str, str, str, str]] = []
    markdown_paths = documentation_markdown_paths(
        root,
        include_generated=False,
    )
    for path in markdown_paths:
        fields = control_fields(path)
        text = path.read_text(encoding="utf-8")
        status = fields.get("Status", adr_status(text))
        document_id = fields.get("Document ID", "Unassigned")
        classification = fields.get("Classification", "Not specified")
        rows.append(
            (
                document_id,
                title_of(path),
                document_category(path, root),
                status,
                f"`{path.relative_to(root)}` ({classification})",
            )
        )
    return "\n".join(
        [
            GENERATED_NOTICE,
            "# Document Register",
            "",
            "This register inventories Markdown documentation. Formal approval must be recorded by an authorized owner; repository presence alone is not approval or certification.",
            "",
            markdown_table(
                ["Document ID", "Title", "Category", "Status", "Source / classification"],
                rows,
            ),
            "",
        ]
    )


def render_all(root: Path) -> dict[str, str]:
    return {
        "docs/_generated/repository-inventory.md": render_repository_inventory(root),
        "docs/_generated/architecture-decision-index.md": render_adr_index(root),
        "docs/_generated/requirements-index.md": render_requirements_index(root),
        "docs/_generated/api-surface.md": render_api_surface(root),
        "docs/_generated/frontend-route-index.md": render_frontend_routes(root),
        "docs/_generated/test-inventory.md": render_test_inventory(root),
        "docs/_generated/document-register.md": render_document_register(root),
    }


def markdown_links(path: Path) -> Iterable[str]:
    text = path.read_text(encoding="utf-8")
    for match in re.finditer(r"(?<!!)\[[^\]]+\]\(([^)]+)\)", text):
        yield match.group(1).strip().split()[0].strip("<>")


def validate_links(root: Path) -> list[str]:
    errors: list[str] = []
    for path in documentation_markdown_paths(root, include_generated=True):
        for target in markdown_links(path):
            if (
                not target
                or target.startswith(("#", "http://", "https://", "mailto:"))
            ):
                continue
            relative_target = target.split("#", 1)[0].split("?", 1)[0]
            if not relative_target:
                continue
            resolved = (path.parent / relative_target).resolve()
            try:
                resolved.relative_to(root.resolve())
            except ValueError:
                errors.append(f"{path.relative_to(root)}: link escapes repository: {target}")
                continue
            if not resolved.exists():
                errors.append(f"{path.relative_to(root)}: missing link target: {target}")
    return errors


def validate_control_metadata(root: Path) -> list[str]:
    errors: list[str] = []
    seen_ids: dict[str, Path] = {}
    docs_root = root / "docs"
    for path in sorted(docs_root.rglob("*.md")):
        relative = path.relative_to(docs_root)
        if not relative.parts or relative.parts[0] not in CONTROLLED_DIRECTORIES:
            continue
        fields = control_fields(path)
        missing = sorted(REQUIRED_CONTROL_FIELDS.difference(fields))
        if missing:
            errors.append(
                f"{path.relative_to(root)}: missing document-control fields: {', '.join(missing)}"
            )
            continue
        document_id = fields["Document ID"]
        previous = seen_ids.get(document_id)
        if previous is not None:
            errors.append(
                f"Duplicate Document ID {document_id}: "
                f"{previous.relative_to(root)} and {path.relative_to(root)}"
            )
        seen_ids[document_id] = path
    return errors


def validate_required_documents(root: Path) -> list[str]:
    return [
        f"Required document is missing: {relative}"
        for relative in sorted(REQUIRED_DOCUMENTS)
        if not (root / relative).is_file()
    ]


def validate_adr_sequence(root: Path) -> list[str]:
    numbers = [
        int(match.group(1))
        for path in (root / "docs/decisions").glob("ADR-*.md")
        if (match := re.match(r"ADR-(\d{3})-", path.name))
    ]
    if not numbers:
        return ["No ADR files were found."]
    expected = list(range(min(numbers), max(numbers) + 1))
    if sorted(numbers) != expected:
        return [f"ADR sequence is not contiguous: found {sorted(numbers)}, expected {expected}"]
    return []


def validate_repository(root: Path) -> list[str]:
    errors: list[str] = []
    errors.extend(validate_required_documents(root))
    errors.extend(validate_control_metadata(root))
    errors.extend(validate_adr_sequence(root))
    errors.extend(validate_links(root))
    return errors


def write_generated(root: Path, rendered: dict[str, str]) -> None:
    for relative, content in rendered.items():
        path = root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content.rstrip() + "\n", encoding="utf-8")


def check_generated(root: Path, rendered: dict[str, str]) -> list[str]:
    stale: list[str] = []
    for relative, content in rendered.items():
        path = root / relative
        expected = content.rstrip() + "\n"
        if not path.is_file() or path.read_text(encoding="utf-8") != expected:
            stale.append(relative)
    extra = {
        str(path.relative_to(root))
        for path in (root / "docs/_generated").glob("*.md")
        if str(path.relative_to(root)) not in GENERATED_PATHS
    } if (root / "docs/_generated").exists() else set()
    stale.extend(f"unexpected generated file: {relative}" for relative in sorted(extra))
    return stale


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="Validate controlled documentation and fail when generated files are stale.",
    )
    args = parser.parse_args()
    root = repository_root()
    rendered = render_all(root)

    if not args.check:
        write_generated(root, rendered)

    validation_errors = validate_repository(root)
    if validation_errors:
        for error in validation_errors:
            print(f"ERROR: {error}", file=sys.stderr)
        return 1

    if args.check:
        stale = check_generated(root, rendered)
        if stale:
            print("Repository documentation is stale:", file=sys.stderr)
            for relative in stale:
                print(f"  - {relative}", file=sys.stderr)
            print("Run `make docs`, review the diff, and commit the generated files.", file=sys.stderr)
            return 1
        print("Repository documentation is current.")
        return 0

    print("Repository documentation generated:")
    for relative in sorted(rendered):
        print(f"  - {relative}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
