from typing import Protocol

from tdp.modules.governance.domain.model import (
    ImpactAssessment,
    RequirementRevision,
    TraceLink,
    WorkflowEvent,
)


class GovernanceRepository(Protocol):
    async def add_requirement(self, revision: RequirementRevision) -> None: ...

    async def add_revision(self, revision: RequirementRevision) -> None: ...

    async def get_requirement_revision(self, revision_id: str) -> RequirementRevision | None: ...

    async def get_latest_requirement(self, project_id: str, key: str) -> RequirementRevision | None: ...

    async def list_latest_requirements(self, project_id: str) -> list[RequirementRevision]: ...

    async def add_trace_link(self, link: TraceLink) -> None: ...

    async def list_trace_links(self, project_id: str) -> list[TraceLink]: ...

    async def list_trace_links_for_target(
        self,
        project_id: str,
        target_type: str,
        target_id: str,
    ) -> list[TraceLink]: ...

    async def add_impact_assessment(self, assessment: ImpactAssessment) -> None: ...

    async def update_impact_assessment(self, assessment: ImpactAssessment) -> None: ...

    async def get_impact_assessment(self, assessment_id: str) -> ImpactAssessment | None: ...

    async def list_impact_assessments(self, project_id: str) -> list[ImpactAssessment]: ...

    async def add_workflow_event(self, event: WorkflowEvent) -> None: ...

    async def list_workflow_events(self, assessment_id: str) -> list[WorkflowEvent]: ...
